### PR TITLE
WIP: Sphinx >= 1.7 compatibility fixes

### PR DESCRIPTION
**Pull request by antaflos**
Contains three changes related to compatibility with Sphinx >= 1.7.

### CODE REVIEW

**Comment by antaflos** [comment]
I've marked this as WIP because the tests fail but I don't know enough about Sphinx and the test setup to verify if the failing tests are because of my changes or if they themselves are broken.

**Comment by bariod** [comment]
Let's hope that @spinus will look into it :eyes:

**Comment by spinus** [comment]
thanks for ping, looking.

**Comment by spinus** [comment]
hey guys, thank you for contribution, but there is already pull request opened for that (#48), what's the point of another one, is the other one not good enough?

**Pull request closed without merging**
