### PR TITLE
Add test for fix to accept images from the docs app

### PR DESCRIPTION
**Pull request by zatan**

### CODE REVIEW

**Comment by spinus** [comment]
@zatan thank you for this. Sorry to be fussy but would you mind using symlink to img.png instead of readding the image? This will keep repo a little smaller.

**Comment by zatan** [comment]
No worries cheers for advice.

**Comment by spinus** [comment]
@zatan OK :-) So one more, could you squash those two commits into one? Currently when you have two commits, the second one use the link but first one still "holds"/reference new image in the repo.
```
git rebase -i HEAD~2  # and select squash or fixup
git push ..... --force
```

**Comment by zatan** [comment]
@spinus hope that makes you happy :)

**Comment by spinus** [comment]
More than happy. Thanks.

**Pull request merged**
